name: Matrix Configuration

on: 
    push: 
    workflow_dispatch: 

jobs:
    run_docker_images_on_multiple_os:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, nginx, alpine]
                exclude:
                    - images: alpine
                      os: windows-latest
                include:
                    - images: amd64/alpine
                      os: ubuntu-20.04
        runs-on: ${{matrix.os}}
        steps:
            - name: Print Docker details
              run: docker info

            - name: Run image on ${{matrix.os}}
              run: docker run ${{matrix.images}}