name: Generate ASCII ArtWork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List Repo file
              run: ls -ltra

            - name: Execute shell script
              run: |
                chmod +x ./shell-script-demo.sh
                ./shell-script-demo.sh


        
